### ISSUE TITLE
DALRC XR20A ESC timeout

### ISSUE THREAD

**Issue by FPVDrone** [blheli-configurator/blheli-configurator#28] opened 2016-12-27 07:03 UTC
[Log - Blheli Configurator App.txt](https://github.com/blheli-configurator/blheli-configurator/files/673670/Log.-.Blheli.Configurator.App.txt)

After I clicked readsetup, it sounded finish but did not show the detail.  Attached is the related log.  Please advise.

Thanks!
Andy

**Comment by DieHertz** [comment] 2016-12-27 09:16
Thanks for reporting, this appears to be a duplicate of #27.

**Closed** 2016-12-27 09:16 UTC
Labels: duplicate

**Comment by DieHertz** [comment] 2016-12-27 11:03
Please try v1.0.3
